"""Run the whole data pipeline end to end.

    python run_pipeline.py              # scrape live, then clean -> load -> query
    python run_pipeline.py --skip-scrape  # reuse the committed data/raw_books.csv

Outputs:
    data/raw_books.csv    raw scraped rows (as listed on the site)
    data/clean_books.csv  cleaned + converted rows
    data/books.db         SQLite database (categories + books)
    query_results.md      every SQL query with its output, plus the
                          read_sql vs merge comparison
"""
import argparse
import sqlite3
from pathlib import Path

import pandas as pd

import scrape
from clean import GBP_TO_INR, clean_books
from database import DB_PATH, build_database
from queries import JOIN_QUERY_INDEX, QUERIES

HERE = Path(__file__).parent
CLEAN_CSV = HERE / "data" / "clean_books.csv"
REPORT = HERE / "query_results.md"


def show(df: pd.DataFrame) -> str:
    return "```\n" + df.to_string(index=False) + "\n```\n"


def merge_version_of_join(categories: pd.DataFrame, books: pd.DataFrame) -> pd.DataFrame:
    """Same result as Q6, built with pandas only (no SQL)."""
    merged = pd.merge(books, categories, on="category_id", how="inner")
    merged = merged[merged["rating"] >= 4]
    merged = merged.sort_values(
        ["category_name", "rating", "price_gbp", "title"],
        ascending=[True, False, False, True],
    )
    return merged[["category_name", "title", "rating", "price_gbp", "price_inr"]].reset_index(drop=True)


def main(skip_scrape: bool):
    # 1. Scrape
    if skip_scrape:
        print(f"[1/5] Skipping scrape, reading {scrape.RAW_CSV.name}")
    else:
        print("[1/5] Scraping books.toscrape.com ...")
        scrape.main()
    raw = pd.read_csv(scrape.RAW_CSV)

    # 2 + 3. Clean and convert
    print("[2/5] Cleaning + converting to INR ...")
    clean = clean_books(raw)
    clean.to_csv(CLEAN_CSV, index=False)
    print(clean.dtypes.to_string())

    # 4 + 5. Build the database
    print("[3/5] Building SQLite database ...")
    categories, books = build_database(clean)
    print(f"      categories: {len(categories)} rows, books: {len(books)} rows -> {DB_PATH.name}")

    # 5. Run the SQL queries
    print("[4/5] Running SQL queries ...")
    out = ["# Data pipeline - query results", ""]
    out.append(f"Generated by `run_pipeline.py`. Rows in `books`: **{len(books)}**, "
               f"categories: **{len(categories)}**, fixed rate used: **1 GBP = {GBP_TO_INR} INR**.\n")
    out.append("## Cleaned data sample\n")
    out.append(show(clean.head(10)))
    out.append("Column types after cleaning:\n")
    out.append("```\n" + clean.dtypes.to_string() + "\n```\n")

    results = {}
    with sqlite3.connect(DB_PATH) as conn:
        for i, (title, clauses, sql) in enumerate(QUERIES):
            # pd.read_sql runs the query and returns a DataFrame directly
            df = pd.read_sql(sql, conn)
            results[i] = df
            out.append(f"## {title}\n")
            out.append(f"Clauses used: {clauses}\n")
            out.append("```sql" + sql + "```\n")
            out.append(f"Output ({len(df)} rows):\n")
            out.append(show(df))

    # 6. read_sql vs merge for the JOIN query
    print("[5/5] Comparing pd.read_sql vs pd.merge for the JOIN query ...")
    sql_df = results[JOIN_QUERY_INDEX]
    merge_df = merge_version_of_join(categories, books)
    pd.testing.assert_frame_equal(sql_df, merge_df, check_dtype=False)

    side_by_side = pd.concat(
        {"pd.read_sql (SQL JOIN)": sql_df[["category_name", "title", "rating", "price_gbp"]],
         "pd.merge (pandas only)": merge_df[["category_name", "title", "rating", "price_gbp"]]},
        axis=1,
    )
    out.append("## Step 6 - `pd.read_sql` vs `pd.merge` for the JOIN query (Q6)\n")
    out.append("`pd.read_sql` ran Q6 inside SQLite. `pd.merge` rebuilt the same result from the "
               "in-memory `books` and `categories` DataFrames with no SQL at all. Every row "
               "of both results is shown side by side:\n")
    out.append(show(side_by_side))
    out.append(f"Row count: read_sql = {len(sql_df)}, merge = {len(merge_df)}. "
               "`pd.testing.assert_frame_equal(sql_df, merge_df)` passed, so **both approaches "
               "return exactly the same rows in the same order.**\n")

    REPORT.write_text("\n".join(out))
    print(f"      Both outputs match ({len(sql_df)} rows). Report written to {REPORT.name}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--skip-scrape", action="store_true",
                        help="use the existing data/raw_books.csv instead of scraping")
    main(parser.parse_args().skip_scrape)
